import os
import json
import re
from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

LM_STUDIO_BASE_URL = os.getenv("LM_STUDIO_BASE_URL", "http://localhost:1234/v1")
LM_STUDIO_MODEL = os.getenv("LM_STUDIO_MODEL", "local-model")

class FixAnalysis(BaseModel):
    error_summary: str
    root_cause: str
    fix_steps: List[str]
    suggested_commands: List[str]
    severity: str
    category: str
    fix_markdown: Optional[str] = None

def build_fix_markdown(fix: Dict[str, Any], logs: str, repo_name: str) -> str:
    timestamp = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S GMT")
    severity_emoji = {
        "low": "🟢", "medium": "🟡", "high": "🟠", "critical": "🔴", "unknown": "⚪"
    }

    steps = "\n".join([f"{i+1}. {s}" for i, s in enumerate(fix.get("fix_steps", []))])
    commands = "\n".join([f"```bash\n{c}\n```" for c in fix.get("suggested_commands", [])]) if fix.get("suggested_commands") else "_No specific commands suggested._"
    
    truncated_logs = logs[:4000] + "\n...(truncated)" if len(logs) > 4000 else logs

    return f"""# AI Self-Healing Report (Powered by LM Studio 🚀)

> **Repo:** `{repo_name}`
> **Generated:** {timestamp}
> **Severity:** {severity_emoji.get(fix.get("severity", "unknown"), "⚪")} `{fix.get("severity", "unknown")}`
> **Category:** `{fix.get("category", "other")}`

---

## Error Summary
{fix.get("error_summary", "No summary provided.")}

---

## Root Cause
{fix.get("root_cause", "Analysis pending.")}

---

## Fix Steps
{steps}

---

## Suggested Commands
{commands}

---

## Raw Logs
<details>
<summary>Click to expand (truncated)</summary>

```
{truncated_logs}
```
</details>

---
*Auto-generated by the Overdrive AI Self-Healing Agent. Review carefully before merging.*
"""

async def analyze_with_ai(logs: str, repo_name: str, error_report: Optional[str] = None) -> FixAnalysis:
    model = ChatOpenAI(
        api_key="lm-studio",
        base_url=LM_STUDIO_BASE_URL,
        model_name=LM_STUDIO_MODEL,
        temperature=0.1
    )

    truncated_logs = logs[:10000] + "\n...(truncated)" if len(logs) > 10000 else logs
    
    error_section = ""
    if error_report:
        error_section = f"""
--- DEPLOYMENT ERROR REPORT (Agent 2) ---
{error_report}
--- END REPORT ---
"""

    prompt = f"""You are a world-class CI/CD and software engineer.
Review the build failure for repository: "{repo_name}".
Analyze the logs and the provided error report to identify the root cause and provide a concrete fix.

{error_section}

Return ONLY a raw JSON object matching this schema:
{{
  "error_summary": "1-line summary",
  "root_cause": "detailed explanation",
  "fix_steps": ["step 1", "step 2"],
  "suggested_commands": ["cmd 1", "cmd 2"],
  "severity": "low|medium|high|critical",
  "category": "dependency|syntax|config|other"
}}

--- BUILD LOGS ---
{truncated_logs}
--- END LOGS ---"""

    try:
        response = await model.ainvoke(prompt)
        content = response.content
        
        # Clean potential markdown blocks
        clean_json = re.sub(r'```json', '', content)
        clean_json = re.sub(r'```', '', clean_json).strip()
        
        analysis_data = json.loads(clean_json)
        
        # Build the PR body (fix_markdown)
        analysis_data["fix_markdown"] = build_fix_markdown(analysis_data, logs, repo_name)
        
        return FixAnalysis(**analysis_data)
        
    except Exception as e:
        print(f"LM Studio Analysis Error: {e}")
        raise ValueError(f"AI Agent failed to analyze logs: {str(e)}")
