"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

/* ─── Types ─────────────────────────────────────────────── */
type LogLevel = "info" | "success" | "warn" | "error" | "debug" | "data" | "section" | "ai";

interface LogLine {
  id: number;
  ts: string;
  level: LogLevel;
  message: string;
  indent?: number;
}

interface PRResult {
  pr_url: string;
  pr_number: number;
  branch_name: string;
}

interface PRHistoryItem {
  id: string;
  timestamp: string;
  repoUrl: string;
  repoName: string;
  prTitle: string;
  pr_url: string;
  pr_number: number;
  branch_name: string;
}

type SessionUser = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};

/* ─── Helpers ─────────────────────────────────────────────── */
let _logId = 0;
function makeLog(level: LogLevel, message: string, indent = 0): LogLine {
  return {
    id: _logId++,
    ts: new Date().toLocaleTimeString("en-US", {
      hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit",
    }),
    level,
    message,
    indent,
  };
}

const LEVEL_STYLES: Record<LogLevel, { color: string; badge: string; bg: string }> = {
  section: { color: "#a78bfa", badge: "▶ ", bg: "rgba(108,99,255,0.06)" },
  info: { color: "#60a5fa", badge: "ℹ ", bg: "transparent" },
  success: { color: "#34d399", badge: "✓ ", bg: "transparent" },
  warn: { color: "#fbbf24", badge: "⚠ ", bg: "rgba(251,191,36,0.04)" },
  error: { color: "#f87171", badge: "✗ ", bg: "rgba(248,113,113,0.05)" },
  debug: { color: "#94a3b8", badge: "· ", bg: "transparent" },
  data: { color: "#e2e8f0", badge: "  ", bg: "transparent" },
  ai: { color: "#c084fc", badge: "🤖 ", bg: "rgba(192,132,252,0.05)" },
};

const SAMPLE_PR_BODY = `## 🔧 AI Self-Healing Report

### Error Summary
The build failed due to a React version mismatch. The \`react-icons\` package requires \`react@^18.2.0\`, but the project uses \`react@19.0.0\`.

### Root Cause
The dependency \`react-icons@4.12.0\` has a peer dependency on \`react@^18.2.0\` which conflicts with the installed \`react@19.0.0\`. Additionally, there is a TypeScript type error where the \`Header\` component does not accept a \`className\` prop.

### Fix Steps
1. Update react-icons to a version compatible with React 19, or install with \`--legacy-peer-deps\`
2. Add \`className\` to the \`Props\` interface of the \`Header\` component
3. Re-run \`npm install\` and \`npm run build\` to verify the fix

### Suggested Commands
\`\`\`bash
npm install react-icons@latest --legacy-peer-deps
npm run build
\`\`\`

---
> This fix was generated by the **Overdrive AI Self-Healing Agent**.`;

/* ─── Component ─────────────────────────────────────────────── */
export default function HealPage() {
  const router = useRouter();
  const [sessionUser, setSessionUser] = useState<SessionUser | null>(null);
  const [checking, setChecking] = useState(true);

  // Form state
  const [repoUrl, setRepoUrl] = useState("");
  const [prTitle, setPrTitle] = useState("");
  const [prBody, setPrBody] = useState("");
  const [loading, setLoading] = useState(false);

  // Console state
  const [repos, setRepos] = useState<any[]>([]);
  const [repoLoading, setRepoLoading] = useState(false);
  const [logsInput, setLogsInput] = useState("");
  const [agentStatus, setAgentStatus] = useState<string | null>(null);

  const [logs, setLogs] = useState<LogLine[]>([]);
  const [hasRun, setHasRun] = useState(false);
  const [lastPR, setLastPR] = useState<PRResult | null>(null);
  const [history, setHistory] = useState<PRHistoryItem[]>([]);

  const consoleRef = useRef<HTMLDivElement>(null);

  // Auth guard
  useEffect(() => {
    fetch("/api/auth/me")
      .then((r) => r.json())
      .then((data) => {
        if (!data.user) router.replace("/");
        else {
          setSessionUser(data.user);
          setChecking(false);
        }
      })
      .catch(() => router.replace("/"));
  }, [router]);

  // Load repos
  useEffect(() => {
    if (!checking && sessionUser) {
      setRepoLoading(true);
      fetch("/api/repo/list")
        .then(r => r.json())
        .then(data => {
          if (data.repos) setRepos(data.repos);
          setRepoLoading(false);
        })
        .catch(() => setRepoLoading(false));
    }
  }, [checking, sessionUser]);

  // Load history
  useEffect(() => {
    if (!checking && sessionUser) {
      fetch("/api/heal/history")
        .then((r) => r.json())
        .then((data) => {
          if (data.history) setHistory(data.history);
        })
        .catch(() => { });
    }
  }, [checking, sessionUser]);

  // Auto-scroll console
  useEffect(() => {
    if (consoleRef.current) {
      consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
    }
  }, [logs]);

  const addLogs = useCallback((newLogs: LogLine[]) => {
    setLogs((prev: LogLine[]) => [...prev, ...newLogs]);
  }, []);

  const clearLogs = useCallback(() => {
    _logId = 0;
    setLogs([]);
    setLastPR(null);
    setPrTitle("");
    setPrBody("");
  }, []);

  /* ─── Agent Analysis handler ─── */
  async function handleAutoHeal() {
    if (!repoUrl || !logsInput.trim() || loading) return;

    clearLogs();
    setHasRun(true);
    setLoading(true);
    setAgentStatus("analyzing");

    const push = (level: LogLevel, msg: string, indent = 0) =>
      setLogs((prev) => [...prev, makeLog(level, msg, indent)]);

    push("section", "🤖 OVERDRIVE AI AGENT INITIALIZED");
    push("info", `Target Repo : ${repoUrl}`, 1);
    push("info", "Starting LangGraph workflow...", 1);
    push("ai", "Thinking: Analyzing logs for root cause...", 1);

    try {
      const res = await fetch("/api/agent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoUrl, logs: logsInput }),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        push("error", `Agent failed: ${data.error || "Unknown error"}`, 1);
        setAgentStatus("failed");
        setLoading(false);
        return;
      }

      setAgentStatus("completed");
      setPrTitle(data.analysis.error_summary);
      setPrBody(data.analysis.fix_markdown);

      push("success", "Analysis complete! Fix generated ✓", 1);
      push("info", `Summary: ${data.analysis.error_summary}`, 1);

      if (data.pr) {
        setLastPR(data.pr);
        push("success", "Pull Request raised automatically! ✓", 1);
        push("data", `PR: ${data.pr.pr_url}`, 1);
      }

      // Refresh history
      fetch("/api/heal/history")
        .then((r) => r.json())
        .then((d) => { if (d.history) setHistory(d.history); })
        .catch(() => { });

    } catch (err) {
      push("error", "Agent connection failed.", 1);
    } finally {
      setLoading(false);
    }
  }



  /* ─── Render ─────────────────────────────────────────────── */
  if (checking) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div className="spinner" style={{ width: 28, height: 28, borderWidth: 3 }} />
      </div>
    );
  }

  const initials = sessionUser?.name?.split(" ").map((w: string) => w[0]).slice(0, 2).join("").toUpperCase() ?? "?";

  return (
    <div style={{ minHeight: "100vh", position: "relative", overflow: "hidden" }}>
      {/* Backgrounds */}
      <div className="bg-grid" />
      <div className="bg-orb bg-orb-1" />
      <div className="bg-orb bg-orb-2" />

      {/* Navbar */}
      <nav className="repo-nav">
        <div className="repo-nav-inner">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <Link href="/dashboard" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none", color: "inherit" }}>
              <div className="logo-mark" style={{ width: 32, height: 32, borderRadius: 9 }}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M13 2L3 14h9l-1 8 10-12h-9z" />
                </svg>
              </div>
              <span style={{ fontWeight: 700, fontSize: "1rem", letterSpacing: "-0.01em" }}>Overdrive</span>
            </Link>
            <span style={{ color: "var(--text-muted)", fontSize: "0.875rem", margin: "0 4px" }}>/</span>
            <span style={{ fontSize: "0.875rem", color: "rgba(240,240,248,0.65)", fontWeight: 500 }}>
              PR Agent
            </span>
            <span className="heal-badge-nav">PR</span>
          </div>

          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{
              display: "flex", alignItems: "center", gap: 8,
              padding: "5px 12px 5px 6px",
              border: "1px solid var(--border)", borderRadius: 999,
              background: "rgba(255,255,255,0.04)",
            }}>
              <div style={{
                width: 26, height: 26, borderRadius: "50%",
                background: "linear-gradient(135deg,var(--accent),#8b5cf6)",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "0.7rem", fontWeight: 700, color: "white",
              }}>
                {initials}
              </div>
              <span style={{ fontSize: "0.8125rem", color: "rgba(240,240,248,0.7)" }}>
                {sessionUser?.name}
              </span>
            </div>
            <Link
              href="/dashboard"
              style={{
                display: "flex", alignItems: "center", gap: 6,
                padding: "7px 14px", borderRadius: 10,
                border: "1px solid var(--border)", background: "var(--surface)",
                color: "rgba(240,240,248,0.65)", fontSize: "0.8125rem",
                textDecoration: "none", fontWeight: 500,
                transition: "border-color 0.2s, color 0.2s",
              }}
              id="link-back-dashboard"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                <path d="M19 12H5M12 5l-7 7 7 7" />
              </svg>
              Dashboard
            </Link>
          </div>
        </div>
      </nav>

      {/* Main layout */}
      <main className="repo-main">

        {/* ── Left panel: Input ── */}
        <aside className="repo-sidebar heal-sidebar">
          <div style={{ marginBottom: 20 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
              <div className="heal-icon-wrap">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="url(#healGrad)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <defs>
                    <linearGradient id="healGrad" x1="0" y1="0" x2="24" y2="24">
                      <stop offset="0%" stopColor="#c084fc" />
                      <stop offset="100%" stopColor="#6c63ff" />
                    </linearGradient>
                  </defs>
                  <path d="M16 3h5v5" />
                  <path d="M21 3l-7 7" />
                  <path d="M11 13l-7 7" />
                  <path d="M3 16v5h5" />
                  <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
                </svg>
              </div>
              <div>
                <h1 style={{ fontSize: "1.2rem", fontWeight: 800, letterSpacing: "-0.02em" }}>
                  PR Agent
                </h1>
                <p style={{ fontSize: "0.75rem", color: "var(--accent-2)", fontWeight: 500 }}>
                  Auto Pull Request Creator
                </p>
              </div>
            </div>
            <p style={{ fontSize: "0.8rem", color: "var(--text-muted)", lineHeight: 1.6 }}>
              Paste the fix content from the AI agent and this will automatically create a branch, commit the fix, and open a Pull Request on the repo.
            </p>
          </div>

          <form
            onSubmit={(e) => { e.preventDefault(); handleAutoHeal(); }}
            style={{ display: "flex", flexDirection: "column", gap: 14 }}
          >
            {/* Repo Selection */}
            <div>
              <label htmlFor="heal-repo-url" className="auth-label">Target Repository</label>
              <div className="input-wrapper">
                <span className="input-icon">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
                  </svg>
                </span>
                <select
                  id="heal-repo-url"
                  value={repoUrl}
                  onChange={(e) => setRepoUrl(e.target.value)}
                  className="auth-input with-icon-left"
                  disabled={loading || repoLoading}
                  style={{ appearance: "none" }}
                >
                  <option value="">{repoLoading ? "Loading your repositories..." : "Select a repository"}</option>
                  {repos.map(r => (
                    <option key={r.id} value={r.html_url}>{r.full_name}</option>
                  ))}
                  <option value="custom">── Custom URL ──</option>
                </select>
              </div>
              {repoUrl === "custom" && (
                <input
                  type="url"
                  placeholder="https://github.com/owner/repo"
                  onChange={(e) => setRepoUrl(e.target.value)}
                  className="auth-input"
                  style={{ marginTop: 8, fontSize: "0.8125rem" }}
                  disabled={loading}
                />
              )}
            </div>

            {/* AI Analysis Section */}
            <div style={{ padding: "14px", background: "rgba(192,132,252,0.06)", borderRadius: 12, border: "1px dashed rgba(192,132,252,0.2)" }}>
              <label htmlFor="heal-logs" className="auth-label" style={{ color: "#c084fc", display: "flex", alignItems: "center", gap: 6 }}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                  <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8z" />
                  <path d="M12 6v6l4 2" />
                </svg>
                AI Agent — Build Logs / Error
              </label>
              <textarea
                id="heal-logs"
                value={logsInput}
                onChange={(e) => setLogsInput(e.target.value)}
                placeholder="Paste your build error or issue description here..."
                className="heal-textarea"
                rows={4}
                style={{ background: "rgba(0,0,0,0.2)", border: "1px solid rgba(255,255,255,0.05)", fontSize: "0.75rem", marginTop: 8 }}
                disabled={loading}
              />
              <button
                type="button"
                onClick={handleAutoHeal}
                disabled={loading || !logsInput.trim() || !repoUrl}
                className="btn-primary"
                style={{
                  marginTop: 10, width: "100%", padding: "8px",
                  background: "linear-gradient(135deg, #c084fc, #6c63ff)",
                  fontSize: "0.75rem"
                }}
              >
                {loading && agentStatus === "analyzing" ? "🤖 Agent Reasoning..." : "Start AI Agent Analysis"}
              </button>
            </div>

            {/* Result — will be populated by AI Agent */}
            {agentStatus === "completed" && (
              <div className="agent-result-preview" style={{
                animation: "slideUp 0.3s ease",
                padding: "16px", background: "rgba(192,132,252,0.06)", borderRadius: 12, border: "1px solid rgba(192,132,252,0.15)"
              }}>
                <h4 style={{ fontSize: "0.8125rem", color: "#c084fc", marginBottom: 12, fontWeight: 700 }}>AI Agent Fix Summary</h4>
                <div style={{ fontSize: "0.875rem", fontWeight: 600, color: "white", marginBottom: 8 }}>{prTitle}</div>
                <div style={{
                  maxHeight: "150px", overflowY: "auto", fontSize: "0.75rem", color: "rgba(255,255,255,0.7)",
                  padding: "10px", background: "rgba(0,0,0,0.3)", borderRadius: 8, whiteSpace: "pre-wrap", border: "1px solid rgba(255,255,255,0.05)"
                }}>
                  {prBody}
                </div>
              </div>
            )}

            {/* Submit button */}
            <button
              id="btn-heal"
              type="submit"
              disabled={loading || agentStatus !== "completed" || !repoUrl.trim()}
              className="btn-primary heal-btn"
              style={{
                background: agentStatus === "completed" ? "linear-gradient(135deg, #6c63ff, #4831ff)" : "rgba(255,255,255,0.05)",
                cursor: agentStatus === "completed" ? "pointer" : "not-allowed"
              }}
            >
              {loading ? (
                <span style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}>
                  <span className="spinner" />
                  Creating PR…
                </span>
              ) : (
                <span style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 3h5v5" />
                    <path d="M21 3l-7 7" />
                    <path d="M11 13l-7 7" />
                    <path d="M3 16v5h5" />
                  </svg>
                  Create Pull Request
                </span>
              )}
            </button>

            {/* Clear */}
            {hasRun && (
              <button
                type="button"
                onClick={() => { clearLogs(); setHasRun(false); }}
                style={{
                  padding: "9px", border: "1px solid var(--border)",
                  borderRadius: 10, background: "transparent",
                  color: "var(--text-muted)", fontSize: "0.8125rem",
                  cursor: "pointer", fontFamily: "inherit", transition: "color 0.15s, border-color 0.15s",
                }}
                id="btn-clear-heal"
              >
                Clear Console
              </button>
            )}
          </form>

          {/* Last PR Result Card */}
          {lastPR && (
            <div className="heal-result-card fade-in" style={{ marginTop: 20 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
                <span className="heal-severity-badge" style={{
                  background: "rgba(52,211,153,0.1)",
                  borderColor: "rgba(52,211,153,0.3)",
                  color: "#34d399",
                }}>
                  ✓ PR CREATED
                </span>
              </div>
              <p style={{ fontSize: "0.8125rem", fontWeight: 600, marginBottom: 6 }}>
                PR #{lastPR.pr_number}
              </p>
              <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", lineHeight: 1.5, marginBottom: 8 }}>
                Branch: {lastPR.branch_name}
              </p>
              <a
                href={lastPR.pr_url}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "inline-flex", alignItems: "center", gap: 6,
                  fontSize: "0.75rem", color: "#c084fc",
                  textDecoration: "none", fontWeight: 600,
                }}
              >
                Open on GitHub →
              </a>
            </div>
          )}

          {/* History */}
          {history.length > 0 && (
            <div style={{ marginTop: 20 }}>
              <p style={{ fontSize: "0.75rem", fontWeight: 600, color: "rgba(240,240,248,0.4)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 10 }}>
                Recent PRs
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {history && history.length > 0 && history.slice(0, 5).map((item: any) => (
                  <div key={item.id} className="heal-history-item">
                    <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}>
                      <span style={{ fontSize: "0.625rem", color: "#34d399" }}>✓</span>
                      <span style={{ fontSize: "0.75rem", fontWeight: 500, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {item.repoName}
                      </span>
                      <span style={{ fontSize: "0.625rem", color: "var(--text-muted)" }}>
                        {new Date(item.timestamp).toLocaleTimeString()}
                      </span>
                    </div>
                    <p style={{ fontSize: "0.7rem", color: "var(--text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                      {item.prTitle}
                    </p>
                    <a href={item.pr_url} target="_blank" rel="noopener noreferrer" style={{ fontSize: "0.675rem", color: "var(--accent-2)", textDecoration: "none", marginTop: 2, display: "inline-block" }}>
                      PR #{item.pr_number} →
                    </a>
                  </div>
                ))}
              </div>
            </div>
          )}
        </aside>

        {/* ── Right panel: Console ── */}
        <section className="repo-console-panel">
          {/* Console header bar */}
          <div className="console-header">
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <div style={{ display: "flex", gap: 6 }}>
                <span style={{ width: 12, height: 12, borderRadius: "50%", background: "#f87171", display: "block" }} />
                <span style={{ width: 12, height: 12, borderRadius: "50%", background: "#fbbf24", display: "block" }} />
                <span style={{ width: 12, height: 12, borderRadius: "50%", background: "#34d399", display: "block" }} />
              </div>
              <span style={{ color: "rgba(240,240,248,0.4)", fontSize: "0.8125rem", marginLeft: 6 }}>
                overdrive — pr agent output
              </span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              {loading && <span className="spinner" style={{ width: 14, height: 14 }} />}
              <span style={{
                fontSize: "0.6875rem", padding: "3px 8px", borderRadius: 6,
                background: loading ? "rgba(192,132,252,0.12)" : logs.length > 0 ? "rgba(52,211,153,0.12)" : "rgba(255,255,255,0.05)",
                color: loading ? "#c084fc" : logs.length > 0 ? "#34d399" : "var(--text-muted)",
                border: `1px solid ${loading ? "rgba(192,132,252,0.25)" : logs.length > 0 ? "rgba(52,211,153,0.25)" : "var(--border)"}`,
                fontFamily: "monospace", fontWeight: 600, letterSpacing: "0.04em",
              }}>
                {loading ? "CREATING" : logs.length > 0 ? "DONE" : "IDLE"}
              </span>
            </div>
          </div>

          {/* Console body */}
          <div
            ref={consoleRef}
            className="console-body"
            id="heal-console-output"
          >
            {logs.length === 0 ? (
              <div style={{ height: "100%", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 16 }}>
                <div className="heal-idle-icon">
                  <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="rgba(192,132,252,0.15)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 3h5v5" />
                    <path d="M21 3l-7 7" />
                    <path d="M11 13l-7 7" />
                    <path d="M3 16v5h5" />
                  </svg>
                </div>
                <p style={{ color: "rgba(240,240,248,0.2)", fontSize: "0.875rem", fontFamily: "monospace", textAlign: "center" }}>
                  Paste fix content and click Create Pull Request to start.
                </p>
                <div style={{ display: "flex", gap: 16, marginTop: 8 }}>
                  {["🌿 Branch", "📝 Commit", "🔀 Pull Request", "🏷️ Labels"].map((step) => (
                    <span key={step} style={{
                      fontSize: "0.6875rem", padding: "4px 10px", borderRadius: 6,
                      background: "rgba(108,99,255,0.06)", border: "1px solid rgba(108,99,255,0.12)",
                      color: "rgba(240,240,248,0.25)",
                    }}>
                      {step}
                    </span>
                  ))}
                </div>
              </div>
            ) : (
              <div style={{ padding: "12px 0" }}>
                {logs.map((log, lineIdx) => {
                  const style = LEVEL_STYLES[log.level];
                  return (
                    <div
                      key={log.id}
                      style={{
                        display: "flex",
                        alignItems: "flex-start",
                        gap: 0,
                        padding: "1.5px 16px",
                        background: style.bg,
                        borderLeft: log.level === "section" ? "2px solid rgba(108,99,255,0.4)"
                          : log.level === "ai" ? "2px solid rgba(192,132,252,0.4)"
                            : "2px solid transparent",
                      }}
                    >
                      {/* Line number */}
                      <span style={{
                        color: "rgba(255,255,255,0.15)",
                        fontSize: "0.7rem",
                        fontFamily: "monospace",
                        minWidth: 32,
                        userSelect: "none",
                        paddingTop: 2,
                        flexShrink: 0,
                      }}>
                        {String(lineIdx + 1).padStart(3, " ")}
                      </span>

                      {/* Timestamp */}
                      <span style={{
                        color: "rgba(255,255,255,0.2)",
                        fontSize: "0.6875rem",
                        fontFamily: "monospace",
                        minWidth: 70,
                        paddingTop: 2,
                        flexShrink: 0,
                      }}>
                        [{log.ts}]
                      </span>

                      {/* Indent + message */}
                      <span style={{
                        color: style.color,
                        fontSize: "0.8125rem",
                        fontFamily: "var(--font-geist-mono), 'Fira Code', 'Cascadia Code', monospace",
                        paddingLeft: (log.indent ?? 0) * 16,
                        lineHeight: 1.6,
                        whiteSpace: "pre-wrap",
                        wordBreak: "break-all",
                      }}>
                        <span style={{ opacity: 0.7, userSelect: "none" }}>{style.badge}</span>
                        {log.message}
                      </span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
