import "server-only";
import { ChatGroq } from "@langchain/groq";
import { z } from "zod";
import type { FixAnalysis, Severity, ErrorCategory } from "./heal-types";

const GROQ_API_KEY = process.env.GROQ_API_KEY;
const GROQ_MODEL = process.env.GROQ_MODEL || "llama-3.3-70b-versatile";

/* ─── Schema for Structured Output ─────────────────────────────────────────── */

const FixAnalysisSchema = z.object({
  error_summary: z.string().describe("Brief 1-line summary of the core error"),
  root_cause: z.string().describe("Detailed 2-4 sentence explanation of why/where the build failed"),
  fix_steps: z.array(z.string()).describe("A list of concrete steps to fix the issue"),
  suggested_commands: z.array(z.string()).describe("Any terminal commands needed to apply the fix"),
  severity: z.enum(["low", "medium", "high", "critical", "unknown"]).describe("The severity level of the error"),
  category: z.string().describe("Category of error: dependency, syntax, config, etc."),
});

/* ─── Analyze logs with Groq (Llama 3) ───────────────────────────────────── */

export async function analyzeWithAI(
  logs: string,
  repoName: string
): Promise<FixAnalysis> {
  if (!GROQ_API_KEY) {
    throw new Error("GROQ_API_KEY is not configured in environment variables.");
  }

  const model = new ChatGroq({
    apiKey: GROQ_API_KEY,
    model: GROQ_MODEL,
    temperature: 0.1,
  }).withStructuredOutput(FixAnalysisSchema);

  const truncatedLogs =
    logs.length > 10000 ? logs.slice(0, 10000) + "\n...(truncated)" : logs;

  const prompt = `You are a world-class CI/CD and software engineer.
Review the build failure for repository: "${repoName}".
Analyze the logs to identify the root cause and provide a concrete fix.

--- BUILD LOGS ---
${truncatedLogs}
--- END LOGS ---

Return a structured analysis including an error summary, root cause, fix steps, and suggested commands.`;

  try {
    const analysis = await model.invoke(prompt) as any;

    // Build the PR body (fix_markdown) from the structured data
    const fix_markdown = buildFixMarkdown(analysis, logs, repoName);
    
    return {
      ...analysis,
      fix_markdown,
    };
  } catch (error) {
    console.error("Groq Analysis Error:", error);
    throw new Error("The AI Agent failed to analyze the logs using Groq.");
  }
}

/* ─── Build fix_error.md content ─────────────────────────────────────────── */

function buildFixMarkdown(
  fix: any,
  logs: string,
  repoName: string
): string {
  const timestamp = new Date().toUTCString();
  const severityEmoji: Record<string, string> = {
    low: "🟢", medium: "🟡", high: "🟠", critical: "🔴", unknown: "⚪"
  };

  const steps = fix.fix_steps
    .map((s: string, i: number) => `${i + 1}. ${s}`)
    .join("\n");

  const commands = fix.suggested_commands.length > 0
    ? fix.suggested_commands.map((c: string) => `\`\`\`bash\n${c}\n\`\`\``).join("\n")
    : "_No specific commands suggested._";

  const truncatedLogs =
    logs.length > 4000 ? logs.slice(0, 4000) + "\n...(truncated)" : logs;

  return `# AI Self-Healing Report (Powered by Groq 🚀)

> **Repo:** \`${repoName}\`
> **Generated:** ${timestamp}
> **Severity:** ${severityEmoji[fix.severity] ?? "⚪"} \`${fix.severity}\`
> **Category:** \`${fix.category}\`

---

## Error Summary
${fix.error_summary}

---

## Root Cause
${fix.root_cause}

---

## Fix Steps
${steps}

---

## Suggested Commands
${commands}

---

## Raw Logs
<details>
<summary>Click to expand (truncated)</summary>

\`\`\`
${truncatedLogs}
\`\`\`
</details>

---
*Auto-generated by the Overdrive AI Self-Healing Agent. Review carefully before merging.*
`;
}
